kind: ConfigMap
apiVersion: v1
metadata:
  name: mysql-schema
data:
  schema.sql: |
    -- Create "quotes" table
    CREATE TABLE `quotes` (`id` bigint NOT NULL AUTO_INCREMENT, `quote` varchar(255) NOT NULL, `author` varchar(255) NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `quote` (`quote`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
