apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasSchema
metadata:
  labels:
    app.kubernetes.io/name: atlasschema
    app.kubernetes.io/instance: atlasschema-sample
    app.kubernetes.io/part-of: atlas-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: atlas-operator
  name: atlasschema-postgres
spec:
  urlFrom:
    secretKeyRef:
      key: url
      name: postgres-credentials
  schema:
    sql: |
      -- demo
      create table users (
        id int not null,
        primary key (id)
      );
