apiVersion: skaffold/v3
kind: Config
metadata:
  name: atlas-operator
build:
  artifacts:
  - image: controller
    docker:
      dockerfile: Dockerfile
      buildArgs:
        OPERATOR_VERSION: v0.0.1-local-k8s
manifests:
  kustomize:
    paths:
    - config/default
profiles:
- name: integration
  manifests:
    kustomize:
      paths:
        - config/default
        - config/integration