# Copyright 2023 The Atlas Operator Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: skaffold/v3
kind: Config
metadata:
  name: atlas-operator
build:
  artifacts:
  - image: controller
    docker:
      dockerfile: Dockerfile
      buildArgs:
        OPERATOR_VERSION: v0.0.1-local-k8s
profiles:
- name: kustomize
  deploy:
    kubectl:
      flags:
        apply: [ --server-side="true" ]
  manifests:
    kustomize:
      paths:
      - config/default
      - config/sqlserver
      - config/customconfig
- name: helm
  deploy:
    kubectl:
      flags:
        apply: [--server-side="true"]
    helm:
      releases:
      - name: atlas-operator
        chartPath: charts/atlas-operator
        namespace: atlas-operator-system
        createNamespace: true
        setValues:
          image:
            repository: controller
            tag: v0.0.1-local-k8s
          extraEnvs:
            - name: MSSQL_ACCEPT_EULA
              value: "Y"
            - name: MSSQL_PID
              value: "Developer"
        valuesFiles:
        - charts/atlas-operator/values.yaml
