# permissions for end users to edit atlasmigrations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: atlasmigration-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: atlas-operator
    app.kubernetes.io/part-of: atlas-operator
    app.kubernetes.io/managed-by: kustomize
  name: atlasmigration-editor-role
rules:
- apiGroups:
  - db.atlasgo.io
  resources:
  - atlasmigrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - db.atlasgo.io
  resources:
  - atlasmigrations/status
  verbs:
  - get
