//go:build !ignore_autogenerated

// Copyright 2023 The Atlas Operator Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AtlasMigration) DeepCopyInto(out *AtlasMigration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AtlasMigration.
func (in *AtlasMigration) DeepCopy() *AtlasMigration {
	if in == nil {
		return nil
	}
	out := new(AtlasMigration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AtlasMigration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AtlasMigrationList) DeepCopyInto(out *AtlasMigrationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AtlasMigration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AtlasMigrationList.
func (in *AtlasMigrationList) DeepCopy() *AtlasMigrationList {
	if in == nil {
		return nil
	}
	out := new(AtlasMigrationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AtlasMigrationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AtlasMigrationSpec) DeepCopyInto(out *AtlasMigrationSpec) {
	*out = *in
	in.TargetSpec.DeepCopyInto(&out.TargetSpec)
	in.ProjectConfigSpec.DeepCopyInto(&out.ProjectConfigSpec)
	in.Cloud.DeepCopyInto(&out.Cloud)
	in.Dir.DeepCopyInto(&out.Dir)
	in.DevURLFrom.DeepCopyInto(&out.DevURLFrom)
	if in.DevDB != nil {
		in, out := &in.DevDB, &out.DevDB
		*out = new(DevDB)
		(*in).DeepCopyInto(*out)
	}
	if in.ProtectedFlows != nil {
		in, out := &in.ProtectedFlows, &out.ProtectedFlows
		*out = new(ProtectFlows)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AtlasMigrationSpec.
func (in *AtlasMigrationSpec) DeepCopy() *AtlasMigrationSpec {
	if in == nil {
		return nil
	}
	out := new(AtlasMigrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AtlasMigrationStatus) DeepCopyInto(out *AtlasMigrationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AtlasMigrationStatus.
func (in *AtlasMigrationStatus) DeepCopy() *AtlasMigrationStatus {
	if in == nil {
		return nil
	}
	out := new(AtlasMigrationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AtlasSchema) DeepCopyInto(out *AtlasSchema) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AtlasSchema.
func (in *AtlasSchema) DeepCopy() *AtlasSchema {
	if in == nil {
		return nil
	}
	out := new(AtlasSchema)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AtlasSchema) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AtlasSchemaList) DeepCopyInto(out *AtlasSchemaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AtlasSchema, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AtlasSchemaList.
func (in *AtlasSchemaList) DeepCopy() *AtlasSchemaList {
	if in == nil {
		return nil
	}
	out := new(AtlasSchemaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AtlasSchemaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AtlasSchemaSpec) DeepCopyInto(out *AtlasSchemaSpec) {
	*out = *in
	in.TargetSpec.DeepCopyInto(&out.TargetSpec)
	in.ProjectConfigSpec.DeepCopyInto(&out.ProjectConfigSpec)
	in.Schema.DeepCopyInto(&out.Schema)
	in.Cloud.DeepCopyInto(&out.Cloud)
	in.DevURLFrom.DeepCopyInto(&out.DevURLFrom)
	if in.DevDB != nil {
		in, out := &in.DevDB, &out.DevDB
		*out = new(DevDB)
		(*in).DeepCopyInto(*out)
	}
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(Policy)
		(*in).DeepCopyInto(*out)
	}
	if in.Schemas != nil {
		in, out := &in.Schemas, &out.Schemas
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AtlasSchemaSpec.
func (in *AtlasSchemaSpec) DeepCopy() *AtlasSchemaSpec {
	if in == nil {
		return nil
	}
	out := new(AtlasSchemaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AtlasSchemaStatus) DeepCopyInto(out *AtlasSchemaStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AtlasSchemaStatus.
func (in *AtlasSchemaStatus) DeepCopy() *AtlasSchemaStatus {
	if in == nil {
		return nil
	}
	out := new(AtlasSchemaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AtlasSecurityReport) DeepCopyInto(out *AtlasSecurityReport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Report.DeepCopyInto(&out.Report)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AtlasSecurityReport.
func (in *AtlasSecurityReport) DeepCopy() *AtlasSecurityReport {
	if in == nil {
		return nil
	}
	out := new(AtlasSecurityReport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AtlasSecurityReport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AtlasSecurityReportList) DeepCopyInto(out *AtlasSecurityReportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AtlasSecurityReport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AtlasSecurityReportList.
func (in *AtlasSecurityReportList) DeepCopy() *AtlasSecurityReportList {
	if in == nil {
		return nil
	}
	out := new(AtlasSecurityReportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AtlasSecurityReportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AtlasSecurityScan) DeepCopyInto(out *AtlasSecurityScan) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AtlasSecurityScan.
func (in *AtlasSecurityScan) DeepCopy() *AtlasSecurityScan {
	if in == nil {
		return nil
	}
	out := new(AtlasSecurityScan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AtlasSecurityScan) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AtlasSecurityScanList) DeepCopyInto(out *AtlasSecurityScanList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AtlasSecurityScan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AtlasSecurityScanList.
func (in *AtlasSecurityScanList) DeepCopy() *AtlasSecurityScanList {
	if in == nil {
		return nil
	}
	out := new(AtlasSecurityScanList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AtlasSecurityScanList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AtlasSecurityScanSpec) DeepCopyInto(out *AtlasSecurityScanSpec) {
	*out = *in
	in.TargetSpec.DeepCopyInto(&out.TargetSpec)
	in.ProjectConfigSpec.DeepCopyInto(&out.ProjectConfigSpec)
	in.Cloud.DeepCopyInto(&out.Cloud)
	if in.Triggers != nil {
		in, out := &in.Triggers, &out.Triggers
		*out = make([]ScanTriggerRef, len(*in))
		copy(*out, *in)
	}
	if in.Suspend != nil {
		in, out := &in.Suspend, &out.Suspend
		*out = new(bool)
		**out = **in
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(ScanPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AtlasSecurityScanSpec.
func (in *AtlasSecurityScanSpec) DeepCopy() *AtlasSecurityScanSpec {
	if in == nil {
		return nil
	}
	out := new(AtlasSecurityScanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AtlasSecurityScanStatus) DeepCopyInto(out *AtlasSecurityScanStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastScan != nil {
		in, out := &in.LastScan, &out.LastScan
		*out = new(ScanAttempt)
		(*in).DeepCopyInto(*out)
	}
	if in.LastSuccessfulTime != nil {
		in, out := &in.LastSuccessfulTime, &out.LastSuccessfulTime
		*out = (*in).DeepCopy()
	}
	if in.LastScheduleTime != nil {
		in, out := &in.LastScheduleTime, &out.LastScheduleTime
		*out = (*in).DeepCopy()
	}
	if in.NextScheduleTime != nil {
		in, out := &in.NextScheduleTime, &out.NextScheduleTime
		*out = (*in).DeepCopy()
	}
	if in.Triggers != nil {
		in, out := &in.Triggers, &out.Triggers
		*out = make([]ObservedTrigger, len(*in))
		copy(*out, *in)
	}
	if in.ActiveWaivers != nil {
		in, out := &in.ActiveWaivers, &out.ActiveWaivers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Summary != nil {
		in, out := &in.Summary, &out.Summary
		*out = new(ScanSummary)
		(*in).DeepCopyInto(*out)
	}
	if in.ReportRef != nil {
		in, out := &in.ReportRef, &out.ReportRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AtlasSecurityScanStatus.
func (in *AtlasSecurityScanStatus) DeepCopy() *AtlasSecurityScanStatus {
	if in == nil {
		return nil
	}
	out := new(AtlasSecurityScanStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckConfig) DeepCopyInto(out *CheckConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckConfig.
func (in *CheckConfig) DeepCopy() *CheckConfig {
	if in == nil {
		return nil
	}
	out := new(CheckConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cloud) DeepCopyInto(out *Cloud) {
	*out = *in
	in.TokenFrom.DeepCopyInto(&out.TokenFrom)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cloud.
func (in *Cloud) DeepCopy() *Cloud {
	if in == nil {
		return nil
	}
	out := new(Cloud)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudV0) DeepCopyInto(out *CloudV0) {
	*out = *in
	in.TokenFrom.DeepCopyInto(&out.TokenFrom)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudV0.
func (in *CloudV0) DeepCopy() *CloudV0 {
	if in == nil {
		return nil
	}
	out := new(CloudV0)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConcurrentIndex) DeepCopyInto(out *ConcurrentIndex) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConcurrentIndex.
func (in *ConcurrentIndex) DeepCopy() *ConcurrentIndex {
	if in == nil {
		return nil
	}
	out := new(ConcurrentIndex)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Credentials) DeepCopyInto(out *Credentials) {
	*out = *in
	in.UserFrom.DeepCopyInto(&out.UserFrom)
	in.PasswordFrom.DeepCopyInto(&out.PasswordFrom)
	in.HostFrom.DeepCopyInto(&out.HostFrom)
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Credentials.
func (in *Credentials) DeepCopy() *Credentials {
	if in == nil {
		return nil
	}
	out := new(Credentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentFlow) DeepCopyInto(out *DeploymentFlow) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentFlow.
func (in *DeploymentFlow) DeepCopy() *DeploymentFlow {
	if in == nil {
		return nil
	}
	out := new(DeploymentFlow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevDB) DeepCopyInto(out *DevDB) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevDB.
func (in *DevDB) DeepCopy() *DevDB {
	if in == nil {
		return nil
	}
	out := new(DevDB)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Diff) DeepCopyInto(out *Diff) {
	*out = *in
	if in.ConcurrentIndex != nil {
		in, out := &in.ConcurrentIndex, &out.ConcurrentIndex
		*out = new(ConcurrentIndex)
		**out = **in
	}
	if in.Skip != nil {
		in, out := &in.Skip, &out.Skip
		*out = new(SkipChanges)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Diff.
func (in *Diff) DeepCopy() *Diff {
	if in == nil {
		return nil
	}
	out := new(Diff)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dir) DeepCopyInto(out *Dir) {
	*out = *in
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	out.Remote = in.Remote
	if in.Local != nil {
		in, out := &in.Local, &out.Local
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dir.
func (in *Dir) DeepCopy() *Dir {
	if in == nil {
		return nil
	}
	out := new(Dir)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GradedPolicy) DeepCopyInto(out *GradedPolicy) {
	*out = *in
	if in.FailOn != nil {
		in, out := &in.FailOn, &out.FailOn
		*out = new(SecurityLevel)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GradedPolicy.
func (in *GradedPolicy) DeepCopy() *GradedPolicy {
	if in == nil {
		return nil
	}
	out := new(GradedPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IgnoredVulnerability) DeepCopyInto(out *IgnoredVulnerability) {
	*out = *in
	in.Waiver.DeepCopyInto(&out.Waiver)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IgnoredVulnerability.
func (in *IgnoredVulnerability) DeepCopy() *IgnoredVulnerability {
	if in == nil {
		return nil
	}
	out := new(IgnoredVulnerability)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LevelCount) DeepCopyInto(out *LevelCount) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LevelCount.
func (in *LevelCount) DeepCopy() *LevelCount {
	if in == nil {
		return nil
	}
	out := new(LevelCount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Lint) DeepCopyInto(out *Lint) {
	*out = *in
	if in.Destructive != nil {
		in, out := &in.Destructive, &out.Destructive
		*out = new(CheckConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Lint.
func (in *Lint) DeepCopy() *Lint {
	if in == nil {
		return nil
	}
	out := new(Lint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservedTrigger) DeepCopyInto(out *ObservedTrigger) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservedTrigger.
func (in *ObservedTrigger) DeepCopy() *ObservedTrigger {
	if in == nil {
		return nil
	}
	out := new(ObservedTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Policy) DeepCopyInto(out *Policy) {
	*out = *in
	if in.Lint != nil {
		in, out := &in.Lint, &out.Lint
		*out = new(Lint)
		(*in).DeepCopyInto(*out)
	}
	if in.Diff != nil {
		in, out := &in.Diff, &out.Diff
		*out = new(Diff)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Policy.
func (in *Policy) DeepCopy() *Policy {
	if in == nil {
		return nil
	}
	out := new(Policy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectConfigSpec) DeepCopyInto(out *ProjectConfigSpec) {
	*out = *in
	in.ConfigFrom.DeepCopyInto(&out.ConfigFrom)
	if in.Vars != nil {
		in, out := &in.Vars, &out.Vars
		*out = make([]Variable, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectConfigSpec.
func (in *ProjectConfigSpec) DeepCopy() *ProjectConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ProjectConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtectFlows) DeepCopyInto(out *ProtectFlows) {
	*out = *in
	if in.MigrateDown != nil {
		in, out := &in.MigrateDown, &out.MigrateDown
		*out = new(DeploymentFlow)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtectFlows.
func (in *ProtectFlows) DeepCopy() *ProtectFlows {
	if in == nil {
		return nil
	}
	out := new(ProtectFlows)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Remote) DeepCopyInto(out *Remote) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Remote.
func (in *Remote) DeepCopy() *Remote {
	if in == nil {
		return nil
	}
	out := new(Remote)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReportedVulnerability) DeepCopyInto(out *ReportedVulnerability) {
	*out = *in
	if in.Waiver != nil {
		in, out := &in.Waiver, &out.Waiver
		*out = new(Waiver)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReportedVulnerability.
func (in *ReportedVulnerability) DeepCopy() *ReportedVulnerability {
	if in == nil {
		return nil
	}
	out := new(ReportedVulnerability)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScanAttempt) DeepCopyInto(out *ScanAttempt) {
	*out = *in
	in.StartTime.DeepCopyInto(&out.StartTime)
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScanAttempt.
func (in *ScanAttempt) DeepCopy() *ScanAttempt {
	if in == nil {
		return nil
	}
	out := new(ScanAttempt)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScanPolicy) DeepCopyInto(out *ScanPolicy) {
	*out = *in
	if in.FailOn != nil {
		in, out := &in.FailOn, &out.FailOn
		*out = new(SecurityLevel)
		**out = **in
	}
	if in.Ignore != nil {
		in, out := &in.Ignore, &out.Ignore
		*out = make([]IgnoredVulnerability, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScanPolicy.
func (in *ScanPolicy) DeepCopy() *ScanPolicy {
	if in == nil {
		return nil
	}
	out := new(ScanPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScanSummary) DeepCopyInto(out *ScanSummary) {
	*out = *in
	if in.Levels != nil {
		in, out := &in.Levels, &out.Levels
		*out = make([]LevelCount, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScanSummary.
func (in *ScanSummary) DeepCopy() *ScanSummary {
	if in == nil {
		return nil
	}
	out := new(ScanSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScanTriggerRef) DeepCopyInto(out *ScanTriggerRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScanTriggerRef.
func (in *ScanTriggerRef) DeepCopy() *ScanTriggerRef {
	if in == nil {
		return nil
	}
	out := new(ScanTriggerRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Schema) DeepCopyInto(out *Schema) {
	*out = *in
	if in.ConfigMapKeyRef != nil {
		in, out := &in.ConfigMapKeyRef, &out.ConfigMapKeyRef
		*out = new(corev1.ConfigMapKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Schema.
func (in *Schema) DeepCopy() *Schema {
	if in == nil {
		return nil
	}
	out := new(Schema)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Secret) DeepCopyInto(out *Secret) {
	*out = *in
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Secret.
func (in *Secret) DeepCopy() *Secret {
	if in == nil {
		return nil
	}
	out := new(Secret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityReport) DeepCopyInto(out *SecurityReport) {
	*out = *in
	in.StartTime.DeepCopyInto(&out.StartTime)
	in.CompletionTime.DeepCopyInto(&out.CompletionTime)
	in.Policy.DeepCopyInto(&out.Policy)
	in.Summary.DeepCopyInto(&out.Summary)
	if in.Extensions != nil {
		in, out := &in.Extensions, &out.Extensions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Vulnerabilities != nil {
		in, out := &in.Vulnerabilities, &out.Vulnerabilities
		*out = make([]ReportedVulnerability, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityReport.
func (in *SecurityReport) DeepCopy() *SecurityReport {
	if in == nil {
		return nil
	}
	out := new(SecurityReport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkipChanges) DeepCopyInto(out *SkipChanges) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkipChanges.
func (in *SkipChanges) DeepCopy() *SkipChanges {
	if in == nil {
		return nil
	}
	out := new(SkipChanges)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetSpec) DeepCopyInto(out *TargetSpec) {
	*out = *in
	in.URLFrom.DeepCopyInto(&out.URLFrom)
	in.Credentials.DeepCopyInto(&out.Credentials)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetSpec.
func (in *TargetSpec) DeepCopy() *TargetSpec {
	if in == nil {
		return nil
	}
	out := new(TargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenFrom) DeepCopyInto(out *TokenFrom) {
	*out = *in
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenFrom.
func (in *TokenFrom) DeepCopy() *TokenFrom {
	if in == nil {
		return nil
	}
	out := new(TokenFrom)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValueFrom) DeepCopyInto(out *ValueFrom) {
	*out = *in
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ConfigMapKeyRef != nil {
		in, out := &in.ConfigMapKeyRef, &out.ConfigMapKeyRef
		*out = new(corev1.ConfigMapKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValueFrom.
func (in *ValueFrom) DeepCopy() *ValueFrom {
	if in == nil {
		return nil
	}
	out := new(ValueFrom)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Variable) DeepCopyInto(out *Variable) {
	*out = *in
	in.ValueFrom.DeepCopyInto(&out.ValueFrom)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Variable.
func (in *Variable) DeepCopy() *Variable {
	if in == nil {
		return nil
	}
	out := new(Variable)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Waiver) DeepCopyInto(out *Waiver) {
	*out = *in
	if in.ExpirationTime != nil {
		in, out := &in.ExpirationTime, &out.ExpirationTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Waiver.
func (in *Waiver) DeepCopy() *Waiver {
	if in == nil {
		return nil
	}
	out := new(Waiver)
	in.DeepCopyInto(out)
	return out
}
