# Copyright 2023 The Atlas Operator Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasMigration
metadata:
  labels:
    app.kubernetes.io/name: atlasmigration
    app.kubernetes.io/instance: atlasmigration-sample
    app.kubernetes.io/part-of: atlas-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: atlas-operator
  name: atlasmigration-sample
spec:
  urlFrom:
    secretKeyRef:
      key: url
      name: db-credentials
  dir:
    local:
      20230316085611.sql: |
        -- Create "users" table
        CREATE TABLE `users` (
          `id` int NOT NULL,
          `user_name` varchar(255) NOT NULL,
          `email` varchar(255) NOT NULL,
          PRIMARY KEY (`id`)
        ) CHARSET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
      20230316090502.sql: |
        -- Create "posts" table
        CREATE TABLE `posts` (
          `id` int NOT NULL,
          `user_id` int NOT NULL,
          `title` varchar(255) NOT NULL,
          `body` text NOT NULL,
          PRIMARY KEY (`id`),
          INDEX `user_id` (`user_id`),
          CONSTRAINT `posts_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE
        ) CHARSET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
      atlas.sum: |
        h1:XBXbh+rzLis8gknjlIqnxXLBkOZ+sN2v2p7KjyVFYYM=
        20230316085611.sql h1:br6W6LPEnnsejlz/7hRm9zthwStCzjN2vZkqVPxlmvo=
        20230316090502.sql h1:GfeRjkSeoCt3JVRtLQNa/r50lRfpAPXS7AqTU2ZNFgY=

